// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eserProje.Data;

#nullable disable

namespace eserProje.Migrations
{
    [DbContext(typeof(eserDbContext))]
    [Migration("20220916174433_bir")]
    partial class bir
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("eserProje.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("MainCategoryID")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.HasIndex("MainCategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Abiye",
                            MainCategoryID = 1
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Elbise",
                            MainCategoryID = 1
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Takım",
                            MainCategoryID = 1
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Tulum",
                            MainCategoryID = 1
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Bluz",
                            MainCategoryID = 1
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Gömlek",
                            MainCategoryID = 1
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "T-Shirt",
                            MainCategoryID = 1
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Ceket",
                            MainCategoryID = 2
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Trençkot",
                            MainCategoryID = 2
                        },
                        new
                        {
                            CategoryID = 10,
                            CategoryName = "Yelek",
                            MainCategoryID = 2
                        },
                        new
                        {
                            CategoryID = 11,
                            CategoryName = "Kot Ceket",
                            MainCategoryID = 2
                        },
                        new
                        {
                            CategoryID = 12,
                            CategoryName = "Mont Kaban",
                            MainCategoryID = 2
                        },
                        new
                        {
                            CategoryID = 13,
                            CategoryName = "Pantolon",
                            MainCategoryID = 3
                        },
                        new
                        {
                            CategoryID = 14,
                            CategoryName = "Jean Pantolon",
                            MainCategoryID = 3
                        },
                        new
                        {
                            CategoryID = 15,
                            CategoryName = "Etek",
                            MainCategoryID = 3
                        },
                        new
                        {
                            CategoryID = 16,
                            CategoryName = "Tayt",
                            MainCategoryID = 3
                        },
                        new
                        {
                            CategoryID = 17,
                            CategoryName = "Eşofman",
                            MainCategoryID = 3
                        },
                        new
                        {
                            CategoryID = 18,
                            CategoryName = "Şort",
                            MainCategoryID = 3
                        });
                });

            modelBuilder.Entity("eserProje.Models.Cloth", b =>
                {
                    b.Property<int>("ClothID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClothID"), 1L, 1);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ClothName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ClothID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Clothes");

                    b.HasData(
                        new
                        {
                            ClothID = 1,
                            CategoryID = 1,
                            ClothName = "Tek Omuz Uzun Abiye - KIRMIZI",
                            Description = "Dummy Text",
                            Price = 649.99m
                        },
                        new
                        {
                            ClothID = 2,
                            CategoryID = 1,
                            ClothName = "Yırtmaç Fırfır Tek Omuz Abiye - KIRMIZI",
                            Description = "Dummy Text",
                            Price = 699.99m
                        },
                        new
                        {
                            ClothID = 3,
                            CategoryID = 1,
                            ClothName = "Göğüs Detay Simli Uzun Abiye - KIRMIZI",
                            Description = "Dummy Text",
                            Price = 649.99m
                        },
                        new
                        {
                            ClothID = 4,
                            CategoryID = 2,
                            ClothName = "Anvelop Yaka Renkli Midi Elbise - PEMBE",
                            Description = "Dummy Text",
                            Price = 242.99m
                        },
                        new
                        {
                            ClothID = 5,
                            CategoryID = 2,
                            ClothName = "Mini Yırtmaçlı Elbise - SİYAH",
                            Description = "Dummy Text",
                            Price = 144.99m
                        },
                        new
                        {
                            ClothID = 6,
                            CategoryID = 2,
                            ClothName = "İri Çiçek Sıfır Kol Midi Elbise - EKRU",
                            Description = "Dummy Text",
                            Price = 139.99m
                        },
                        new
                        {
                            ClothID = 7,
                            CategoryID = 3,
                            ClothName = "Oversize Keten Takım - YAĞ YEŞİLİ",
                            Description = "Dummy Text",
                            Price = 427.49m
                        },
                        new
                        {
                            ClothID = 8,
                            CategoryID = 3,
                            ClothName = "Ceket Pantolon Takım - KIRMIZI",
                            Description = "Dummy Text",
                            Price = 719.99m
                        },
                        new
                        {
                            ClothID = 9,
                            CategoryID = 3,
                            ClothName = "Ceket Pantolon Takım - SİYAH",
                            Description = "Dummy Text",
                            Price = 719.99m
                        },
                        new
                        {
                            ClothID = 10,
                            CategoryID = 4,
                            ClothName = "Bol Paça Ayrobin Tulum - SİYAH",
                            Description = "Dummy Text",
                            Price = 215.99m
                        },
                        new
                        {
                            ClothID = 11,
                            CategoryID = 4,
                            ClothName = "Kol Fırfır Klasik Tulum - SİYAH",
                            Description = "Dummy Text",
                            Price = 269.99m
                        },
                        new
                        {
                            ClothID = 12,
                            CategoryID = 4,
                            ClothName = "Bel Dekolteli Tulum - YAĞ YEŞİLİ",
                            Description = "Dummy Text",
                            Price = 819.99m
                        },
                        new
                        {
                            ClothID = 13,
                            CategoryID = 5,
                            ClothName = "Vatkalı Degaje Bluz - BEYAZ",
                            Description = "Dummy Text",
                            Price = 149.99m
                        },
                        new
                        {
                            ClothID = 14,
                            CategoryID = 5,
                            ClothName = "Vatkalı Degaje Bluz - SİYAH",
                            Description = "Dummy Text",
                            Price = 149.99m
                        },
                        new
                        {
                            ClothID = 15,
                            CategoryID = 5,
                            ClothName = "Kare Yaka Yan Bağcıklı Bluz - BEJ",
                            Description = "Dummy Text",
                            Price = 139.99m
                        },
                        new
                        {
                            ClothID = 16,
                            CategoryID = 6,
                            ClothName = "Kuşaklı Ekose Gömlek - LİLA",
                            Description = "Dummy Text",
                            Price = 84.99m
                        },
                        new
                        {
                            ClothID = 17,
                            CategoryID = 6,
                            ClothName = "Oversize Salaş Gömlek - BEYAZ",
                            Description = "Dummy Text",
                            Price = 206.99m
                        },
                        new
                        {
                            ClothID = 18,
                            CategoryID = 6,
                            ClothName = "Tek Cep Oversize Gömlek - YEŞİL",
                            Description = "Dummy Text",
                            Price = 179.99m
                        },
                        new
                        {
                            ClothID = 19,
                            CategoryID = 7,
                            ClothName = "Vatkalı Düz T-Shirt - BEYAZ",
                            Description = "Dummy Text",
                            Price = 99.99m
                        },
                        new
                        {
                            ClothID = 20,
                            CategoryID = 7,
                            ClothName = "V Yaka Kısa Kollu T-Shirt - BEYAZ",
                            Description = "Dummy Text",
                            Price = 119.99m
                        },
                        new
                        {
                            ClothID = 21,
                            CategoryID = 7,
                            ClothName = "Kol Kat Yan Yırtmaçlı T-Shirt - SİYAH",
                            Description = "Dummy Text",
                            Price = 119.99m
                        },
                        new
                        {
                            ClothID = 22,
                            CategoryID = 8,
                            ClothName = "Gizli Cep Vatkalı Blazer Ceket - CAMEL",
                            Description = "Dummy Text",
                            Price = 517.49m
                        },
                        new
                        {
                            ClothID = 23,
                            CategoryID = 8,
                            ClothName = "Atlas Kumaş Blazer Ceket - SAKS",
                            Description = "Dummy Text",
                            Price = 517.49m
                        },
                        new
                        {
                            ClothID = 24,
                            CategoryID = 8,
                            ClothName = "Kruvaze Yaka Blazer Ceket - CAMEL",
                            Description = "Dummy Text",
                            Price = 517.49m
                        },
                        new
                        {
                            ClothID = 25,
                            CategoryID = 9,
                            ClothName = "Kadife Yaka Cepli Trençkot - TAŞ",
                            Description = "Dummy Text",
                            Price = 607.49m
                        },
                        new
                        {
                            ClothID = 26,
                            CategoryID = 9,
                            ClothName = "Garnili Trençkot - BEJ",
                            Description = "Dummy Text",
                            Price = 737.99m
                        },
                        new
                        {
                            ClothID = 27,
                            CategoryID = 9,
                            ClothName = "Kadife Yaka Cepli Trençkot - HAKİ",
                            Description = "Dummy Text",
                            Price = 607.49m
                        },
                        new
                        {
                            ClothID = 28,
                            CategoryID = 10,
                            ClothName = "Garnili Şişme Yelek - HAKİ",
                            Description = "Dummy Text",
                            Price = 494.99m
                        },
                        new
                        {
                            ClothID = 29,
                            CategoryID = 10,
                            ClothName = "Şişme Yelek - SİYAH",
                            Description = "Dummy Text",
                            Price = 449.99m
                        },
                        new
                        {
                            ClothID = 30,
                            CategoryID = 10,
                            ClothName = "Gizli Fermuarlı Şişme Yelek - SİYAH",
                            Description = "Dummy Text",
                            Price = 449.99m
                        },
                        new
                        {
                            ClothID = 31,
                            CategoryID = 11,
                            ClothName = "Gold Fermuarlı Denim Ceket - FÜME",
                            Description = "Dummy Text",
                            Price = 314.99m
                        },
                        new
                        {
                            ClothID = 32,
                            CategoryID = 11,
                            ClothName = "Gold Fermuarlı Denim Ceket - MAVİ",
                            Description = "Dummy Text",
                            Price = 314.99m
                        },
                        new
                        {
                            ClothID = 33,
                            CategoryID = 11,
                            ClothName = "Kol Taş Detaylı Kot Ceket - FÜME",
                            Description = "Dummy Text",
                            Price = 170.99m
                        },
                        new
                        {
                            ClothID = 34,
                            CategoryID = 12,
                            ClothName = "Dikiş Desen Mevsimlik Mont - HAKİ",
                            Description = "Dummy Text",
                            Price = 499.99m
                        },
                        new
                        {
                            ClothID = 35,
                            CategoryID = 12,
                            ClothName = "Çiçek Nakışlı Mevsimlik Mont - BEYAZ",
                            Description = "Dummy Text",
                            Price = 649.99m
                        },
                        new
                        {
                            ClothID = 36,
                            CategoryID = 12,
                            ClothName = "Kuşaklı Kaşe Kaban - CAMEL",
                            Description = "Dummy Text",
                            Price = 1499.99m
                        },
                        new
                        {
                            ClothID = 37,
                            CategoryID = 13,
                            ClothName = "Cepli Palazzo Pantolon - BEJ",
                            Description = "Dummy Text",
                            Price = 247.49m
                        },
                        new
                        {
                            ClothID = 38,
                            CategoryID = 13,
                            ClothName = "Cepli Palazzo Pantolon - SİYAH",
                            Description = "Dummy Text",
                            Price = 247.49m
                        },
                        new
                        {
                            ClothID = 39,
                            CategoryID = 13,
                            ClothName = "Yüksek Bel Kemerli Kumaş Pantolon - SİYAH",
                            Description = "Dummy Text",
                            Price = 224.99m
                        },
                        new
                        {
                            ClothID = 40,
                            CategoryID = 14,
                            ClothName = "Yüksekbel Skinny Pantolon - SİYAH",
                            Description = "Dummy Text",
                            Price = 149.99m
                        },
                        new
                        {
                            ClothID = 41,
                            CategoryID = 14,
                            ClothName = "Yüksekbel Skinny Pantolon - LACİVERT",
                            Description = "Dummy Text",
                            Price = 149.99m
                        },
                        new
                        {
                            ClothID = 42,
                            CategoryID = 14,
                            ClothName = "Skinny Fit Jean - MAVİ",
                            Description = "Dummy Text",
                            Price = 174.99m
                        },
                        new
                        {
                            ClothID = 43,
                            CategoryID = 15,
                            ClothName = "Yırtmaçlı Saten Etek - SİYAH",
                            Description = "Dummy Text",
                            Price = 233.99m
                        },
                        new
                        {
                            ClothID = 44,
                            CategoryID = 15,
                            ClothName = "Kruvaze Midi Etek - SİYAH",
                            Description = "Dummy Text",
                            Price = 224.99m
                        },
                        new
                        {
                            ClothID = 45,
                            CategoryID = 15,
                            ClothName = "Yan Yırtmaçlı Midi Etek - KREM",
                            Description = "Dummy Text",
                            Price = 149.99m
                        },
                        new
                        {
                            ClothID = 46,
                            CategoryID = 16,
                            ClothName = "Korse Etkili Tayt - MÜRDÜM",
                            Description = "Dummy Text",
                            Price = 129.99m
                        },
                        new
                        {
                            ClothID = 47,
                            CategoryID = 16,
                            ClothName = "İspanyol Paça Fitilli Tayt - FÜME",
                            Description = "Dummy Text",
                            Price = 139.99m
                        },
                        new
                        {
                            ClothID = 48,
                            CategoryID = 16,
                            ClothName = "İspanyol Paça Fitilli Tayt - BEJ",
                            Description = "Dummy Text",
                            Price = 139.99m
                        },
                        new
                        {
                            ClothID = 49,
                            CategoryID = 17,
                            ClothName = "Paça Lastik Eşofman - SİYAH",
                            Description = "Dummy Text",
                            Price = 179.99m
                        },
                        new
                        {
                            ClothID = 50,
                            CategoryID = 17,
                            ClothName = "Paça Lastik Eşofman - GRİ",
                            Description = "Dummy Text",
                            Price = 179.99m
                        },
                        new
                        {
                            ClothID = 51,
                            CategoryID = 17,
                            ClothName = "Bol Paça Eşofman - GRİ",
                            Description = "Dummy Text",
                            Price = 124.99m
                        },
                        new
                        {
                            ClothID = 52,
                            CategoryID = 18,
                            ClothName = "Yüksek Bel Denim Şort - MAVİ",
                            Description = "Dummy Text",
                            Price = 179.99m
                        },
                        new
                        {
                            ClothID = 53,
                            CategoryID = 18,
                            ClothName = "Palazzo Şort - SARI",
                            Description = "Dummy Text",
                            Price = 134.99m
                        },
                        new
                        {
                            ClothID = 54,
                            CategoryID = 18,
                            ClothName = "Palazzo Şort - PEMBE",
                            Description = "Dummy Text",
                            Price = 134.99m
                        });
                });

            modelBuilder.Entity("eserProje.Models.Likee", b =>
                {
                    b.Property<int>("LikeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LikeeID"), 1L, 1);

                    b.Property<int>("ClothID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LikeeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserrID")
                        .HasColumnType("int");

                    b.HasKey("LikeeID");

                    b.HasIndex("ClothID");

                    b.HasIndex("UserrID");

                    b.ToTable("Likees");

                    b.HasData(
                        new
                        {
                            LikeeID = 1,
                            ClothID = 1,
                            LikeeDate = new DateTime(2022, 6, 23, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            UserrID = 2
                        },
                        new
                        {
                            LikeeID = 2,
                            ClothID = 3,
                            LikeeDate = new DateTime(2022, 6, 23, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            UserrID = 2
                        },
                        new
                        {
                            LikeeID = 3,
                            ClothID = 2,
                            LikeeDate = new DateTime(2022, 6, 23, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            UserrID = 2
                        },
                        new
                        {
                            LikeeID = 4,
                            ClothID = 3,
                            LikeeDate = new DateTime(2022, 6, 23, 11, 12, 0, 0, DateTimeKind.Unspecified),
                            UserrID = 1
                        },
                        new
                        {
                            LikeeID = 5,
                            ClothID = 2,
                            LikeeDate = new DateTime(2022, 6, 23, 11, 1, 0, 0, DateTimeKind.Unspecified),
                            UserrID = 1
                        });
                });

            modelBuilder.Entity("eserProje.Models.MainCategory", b =>
                {
                    b.Property<int>("MainCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MainCategoryID"), 1L, 1);

                    b.Property<string>("MainCategoryName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("MainCategoryID");

                    b.ToTable("MainCategories");

                    b.HasData(
                        new
                        {
                            MainCategoryID = 1,
                            MainCategoryName = "Üst Giyim"
                        },
                        new
                        {
                            MainCategoryID = 2,
                            MainCategoryName = "Dış Giyim"
                        },
                        new
                        {
                            MainCategoryID = 3,
                            MainCategoryName = "Alt Giyim"
                        });
                });

            modelBuilder.Entity("eserProje.Models.Rolee", b =>
                {
                    b.Property<int>("RoleeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleeID"), 1L, 1);

                    b.Property<string>("RoleeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoleeID");

                    b.ToTable("Rolees");

                    b.HasData(
                        new
                        {
                            RoleeID = 1,
                            RoleeName = "Candidate"
                        },
                        new
                        {
                            RoleeID = 2,
                            RoleeName = "Client"
                        },
                        new
                        {
                            RoleeID = 3,
                            RoleeName = "Admin"
                        },
                        new
                        {
                            RoleeID = 4,
                            RoleeName = "Owner"
                        },
                        new
                        {
                            RoleeID = 5,
                            RoleeName = "Supervisor"
                        });
                });

            modelBuilder.Entity("eserProje.Models.Userr", b =>
                {
                    b.Property<int>("UserrID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserrID"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(52)
                        .HasColumnType("nvarchar(52)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleeID")
                        .HasColumnType("int");

                    b.HasKey("UserrID");

                    b.HasIndex("RoleeID");

                    b.ToTable("Userrs");

                    b.HasData(
                        new
                        {
                            UserrID = 1,
                            Email = "abc@hotmail.com",
                            Password = "12345678",
                            RoleeID = 2
                        },
                        new
                        {
                            UserrID = 2,
                            Email = "xyz@hotmail.com",
                            Password = "12345678",
                            RoleeID = 1
                        },
                        new
                        {
                            UserrID = 3,
                            Email = "aliveli@hotmail.com",
                            Password = "12345678",
                            RoleeID = 5
                        },
                        new
                        {
                            UserrID = 4,
                            Email = "admin@admin.com",
                            Password = "123123123",
                            RoleeID = 3
                        });
                });

            modelBuilder.Entity("eserProje.Models.Category", b =>
                {
                    b.HasOne("eserProje.Models.MainCategory", "MainCategory")
                        .WithMany()
                        .HasForeignKey("MainCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("eserProje.Models.Cloth", b =>
                {
                    b.HasOne("eserProje.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("eserProje.Models.Likee", b =>
                {
                    b.HasOne("eserProje.Models.Cloth", "Cloth")
                        .WithMany()
                        .HasForeignKey("ClothID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eserProje.Models.Userr", "Userr")
                        .WithMany()
                        .HasForeignKey("UserrID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cloth");

                    b.Navigation("Userr");
                });

            modelBuilder.Entity("eserProje.Models.Userr", b =>
                {
                    b.HasOne("eserProje.Models.Rolee", "Rolee")
                        .WithMany()
                        .HasForeignKey("RoleeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rolee");
                });
#pragma warning restore 612, 618
        }
    }
}
